export const correlationIdHeader = {
  description:
    'Optional correlation id. If omitted, the gateway creates one and propagates it internally.',
  example: '7f4d9c7a-6b8f-4a9e-9d2b-4c8f7a1e2d30',
  name: 'x-correlation-id',
  required: false,
};

export const errorResponseSchema = {
  example: {
    correlationId: '7f4d9c7a-6b8f-4a9e-9d2b-4c8f7a1e2d30',
    error: 'Bad Request',
    message: 'Validation failed',
    statusCode: 400,
    timestamp: '2026-06-06T12:00:00.000Z',
  },
  properties: {
    correlationId: { type: 'string' },
    error: { type: 'string' },
    message: {
      oneOf: [{ type: 'string' }, { items: { type: 'string' }, type: 'array' }],
    },
    statusCode: { type: 'number' },
    timestamp: { format: 'date-time', type: 'string' },
  },
  required: ['message', 'statusCode', 'timestamp'],
  type: 'object',
};

export const authResponseSchema = {
  example: {
    tokens: {
      accessToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
      expiresInSeconds: 900,
      refreshToken: 'refresh-token-value',
      tokenType: 'Bearer',
    },
    user: {
      email: 'customer@northlane.test',
      role: 'USER',
      userId: 'f0a9c3b2-6d1e-4f8a-9b20-7c3d2e1f4a68',
    },
  },
  properties: {
    tokens: {
      properties: {
        accessToken: { type: 'string' },
        expiresInSeconds: { type: 'number' },
        refreshToken: { type: 'string' },
        tokenType: { enum: ['Bearer'], type: 'string' },
      },
      required: ['accessToken', 'expiresInSeconds', 'refreshToken', 'tokenType'],
      type: 'object',
    },
    user: {
      properties: {
        email: { format: 'email', type: 'string' },
        role: { enum: ['ADMIN', 'USER'], type: 'string' },
        userId: { type: 'string' },
      },
      required: ['email', 'role', 'userId'],
      type: 'object',
    },
  },
  required: ['tokens', 'user'],
  type: 'object',
};

export const categorySchema = {
  properties: {
    createdAt: { format: 'date-time', type: 'string' },
    description: { type: 'string' },
    id: { type: 'string' },
    imageUrl: { format: 'uri', type: 'string' },
    isActive: { type: 'boolean' },
    name: { type: 'string' },
    parentId: { type: 'string' },
    slug: { type: 'string' },
    updatedAt: { format: 'date-time', type: 'string' },
  },
  required: ['createdAt', 'id', 'isActive', 'name', 'slug', 'updatedAt'],
  type: 'object',
};

export const productVariantSchema = {
  properties: {
    availableStock: { type: 'number' },
    barcode: { type: 'string' },
    colorHex: { type: 'string' },
    colorName: { type: 'string' },
    id: { type: 'string' },
    isActive: { type: 'boolean' },
    priceOverride: { type: 'number' },
    reservedStock: { type: 'number' },
    size: { type: 'string' },
    sku: { type: 'string' },
    stock: { type: 'number' },
    weightInGrams: { type: 'number' },
  },
  required: [
    'availableStock',
    'colorHex',
    'colorName',
    'id',
    'isActive',
    'reservedStock',
    'size',
    'sku',
    'stock',
    'weightInGrams',
  ],
  type: 'object',
};

export const productImageSchema = {
  properties: {
    altText: { type: 'string' },
    id: { type: 'string' },
    isPrimary: { type: 'boolean' },
    position: { type: 'number' },
    url: { format: 'uri', type: 'string' },
    variantId: { type: 'string' },
  },
  required: ['altText', 'id', 'isPrimary', 'position', 'url'],
  type: 'object',
};

export const productSchema = {
  example: {
    averageRating: 0,
    brand: 'Devre',
    careInstructions: 'Lavar con agua fria. No usar secadora.',
    categoryId: '2b3c4d5e-6f7a-4890-b123-23456789abcd',
    categoryName: 'Camperas',
    composition: '100% Poliamida',
    createdAt: '2026-06-06T12:00:00.000Z',
    currency: 'ARS',
    description: 'Campera inflada negra de corte corto y cuello alto.',
    discountPercentage: 0,
    fit: 'REGULAR',
    genderTarget: 'MEN',
    id: 'f0a9c3b2-6d1e-4f8a-9b20-7c3d2e1f4a68',
    images: [],
    isActive: true,
    isBestSeller: false,
    isFeatured: true,
    isNewArrival: true,
    material: 'Poliamida',
    price: 59990,
    productType: 'JACKET',
    shortDescription: 'Campera inflada negra con cuello alto.',
    skuBase: 'DEV-JACKET-BLK',
    season: 'WINTER',
    slug: 'campera_inflada_negra',
    tags: ['camperas', 'invierno'],
    taxRate: 0,
    title: 'Campera Inflada Negra',
    totalReviews: 0,
    updatedAt: '2026-06-06T12:00:00.000Z',
    variants: [],
  },
  properties: {
    averageRating: { type: 'number' },
    brand: { type: 'string' },
    canonicalUrl: { type: 'string' },
    careInstructions: { type: 'string' },
    categoryId: { type: 'string' },
    categoryName: { type: 'string' },
    collection: { type: 'string' },
    compareAtPrice: { type: 'number' },
    composition: { type: 'string' },
    costPrice: { type: 'number' },
    createdAt: { format: 'date-time', type: 'string' },
    currency: { type: 'string' },
    description: { type: 'string' },
    discountPercentage: { type: 'number' },
    externalUrl: { type: 'string' },
    fit: { enum: ['OVERSIZED', 'REGULAR', 'RELAXED', 'SLIM'], type: 'string' },
    genderTarget: { enum: ['KIDS', 'MEN', 'UNISEX', 'WOMEN'], type: 'string' },
    id: { type: 'string' },
    images: { items: productImageSchema, type: 'array' },
    isActive: { type: 'boolean' },
    isBestSeller: { type: 'boolean' },
    isFeatured: { type: 'boolean' },
    isNewArrival: { type: 'boolean' },
    material: { type: 'string' },
    price: { type: 'number' },
    productType: {
      enum: [
        'ACCESSORY',
        'DRESS',
        'HOODIE',
        'JACKET',
        'JEANS',
        'OTHER',
        'PANTS',
        'SHIRT',
        'SHOES',
        'SWEATER',
        'T_SHIRT',
      ],
      type: 'string',
    },
    seoDescription: { type: 'string' },
    seoTitle: { type: 'string' },
    shortDescription: { type: 'string' },
    skuBase: { type: 'string' },
    season: { enum: ['ALL_SEASON', 'MID_SEASON', 'SUMMER', 'WINTER'], type: 'string' },
    slug: { type: 'string' },
    subcategoryId: { type: 'string' },
    subcategoryName: { type: 'string' },
    tags: { items: { type: 'string' }, type: 'array' },
    taxRate: { type: 'number' },
    title: { type: 'string' },
    totalReviews: { type: 'number' },
    updatedAt: { format: 'date-time', type: 'string' },
    variants: { items: productVariantSchema, type: 'array' },
  },
  required: [
    'averageRating',
    'brand',
    'careInstructions',
    'categoryId',
    'categoryName',
    'composition',
    'createdAt',
    'currency',
    'description',
    'discountPercentage',
    'fit',
    'genderTarget',
    'id',
    'images',
    'isActive',
    'isBestSeller',
    'isFeatured',
    'isNewArrival',
    'material',
    'price',
    'productType',
    'shortDescription',
    'skuBase',
    'season',
    'slug',
    'tags',
    'taxRate',
    'title',
    'totalReviews',
    'updatedAt',
    'variants',
  ],
  type: 'object',
};

export const productListResponseSchema = {
  example: {
    filters: {
      brands: ['Devre'],
      categories: [],
      colors: ['Negro', 'Gris oscuro'],
      sizes: ['S', 'M', 'L', 'XL'],
    },
    items: [productSchema.example],
    total: 1,
  },
  properties: {
    filters: {
      properties: {
        brands: { items: { type: 'string' }, type: 'array' },
        categories: { items: categorySchema, type: 'array' },
        colors: { items: { type: 'string' }, type: 'array' },
        sizes: { items: { type: 'string' }, type: 'array' },
      },
      required: ['brands', 'categories', 'colors', 'sizes'],
      type: 'object',
    },
    items: { items: productSchema, type: 'array' },
    total: { type: 'number' },
  },
  required: ['filters', 'items', 'total'],
  type: 'object',
};

export const cartItemSchema = {
  properties: {
    createdAt: { format: 'date-time', type: 'string' },
    id: { type: 'string' },
    imageSnapshot: { type: 'string' },
    productId: { type: 'string' },
    quantity: { type: 'number' },
    selectedColor: { type: 'string' },
    selectedSize: { type: 'string' },
    sku: { type: 'string' },
    slugSnapshot: { type: 'string' },
    titleSnapshot: { type: 'string' },
    total: { type: 'number' },
    unitPriceSnapshot: { type: 'number' },
    updatedAt: { format: 'date-time', type: 'string' },
    variantId: { type: 'string' },
  },
  required: [
    'createdAt',
    'id',
    'productId',
    'quantity',
    'selectedColor',
    'selectedSize',
    'sku',
    'slugSnapshot',
    'titleSnapshot',
    'total',
    'unitPriceSnapshot',
    'updatedAt',
    'variantId',
  ],
  type: 'object',
};

export const cartSchema = {
  example: {
    createdAt: '2026-06-06T12:00:00.000Z',
    currency: 'ARS',
    id: 'cart-123',
    items: [],
    status: 'ACTIVE',
    subtotal: 0,
    updatedAt: '2026-06-06T12:00:00.000Z',
    userId: 'f0a9c3b2-6d1e-4f8a-9b20-7c3d2e1f4a68',
  },
  properties: {
    createdAt: { format: 'date-time', type: 'string' },
    currency: { type: 'string' },
    id: { type: 'string' },
    items: { items: cartItemSchema, type: 'array' },
    status: { enum: ['ABANDONED', 'ACTIVE', 'CHECKED_OUT'], type: 'string' },
    subtotal: { type: 'number' },
    updatedAt: { format: 'date-time', type: 'string' },
    userId: { type: 'string' },
  },
  required: ['createdAt', 'currency', 'id', 'items', 'status', 'subtotal', 'updatedAt', 'userId'],
  type: 'object',
};

export const paymentSchema = {
  example: {
    amount: 59990,
    checkoutUrl: 'https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=123',
    createdAt: '2026-06-06T12:00:00.000Z',
    currency: 'ARS',
    id: 'payment-123',
    idempotencyKey: 'checkout-20260606-001',
    orderId: 'order-123',
    provider: 'MERCADO_PAGO',
    providerPreferenceId: 'pref-123',
    status: 'PENDING',
    updatedAt: '2026-06-06T12:00:00.000Z',
    userId: 'f0a9c3b2-6d1e-4f8a-9b20-7c3d2e1f4a68',
  },
  properties: {
    amount: { type: 'number' },
    checkoutUrl: { type: 'string' },
    createdAt: { format: 'date-time', type: 'string' },
    currency: { type: 'string' },
    externalReference: { type: 'string' },
    failureReason: { type: 'string' },
    id: { type: 'string' },
    idempotencyKey: { type: 'string' },
    initPoint: { type: 'string' },
    metadata: { additionalProperties: true, type: 'object' },
    orderId: { type: 'string' },
    provider: { enum: ['MERCADO_PAGO', 'MOCK', 'STRIPE'], type: 'string' },
    providerPaymentId: { type: 'string' },
    providerPreferenceId: { type: 'string' },
    rawProviderStatus: { type: 'string' },
    sandboxInitPoint: { type: 'string' },
    status: {
      enum: ['APPROVED', 'CANCELLED', 'EXPIRED', 'IN_PROCESS', 'PENDING', 'REFUNDED', 'REJECTED'],
      type: 'string',
    },
    updatedAt: { format: 'date-time', type: 'string' },
    userId: { type: 'string' },
  },
  required: [
    'amount',
    'createdAt',
    'currency',
    'id',
    'idempotencyKey',
    'orderId',
    'provider',
    'status',
    'updatedAt',
    'userId',
  ],
  type: 'object',
};

export const orderItemSchema = {
  properties: {
    brand: { type: 'string' },
    category: { type: 'string' },
    createdAt: { format: 'date-time', type: 'string' },
    id: { type: 'string' },
    productId: { type: 'string' },
    productImage: { type: 'string' },
    productSlug: { type: 'string' },
    productTitle: { type: 'string' },
    quantity: { type: 'number' },
    selectedColor: { type: 'string' },
    selectedSize: { type: 'string' },
    sku: { type: 'string' },
    total: { type: 'number' },
    unitPrice: { type: 'number' },
    variantId: { type: 'string' },
  },
  required: [
    'createdAt',
    'id',
    'productId',
    'productSlug',
    'productTitle',
    'quantity',
    'selectedColor',
    'selectedSize',
    'sku',
    'total',
    'unitPrice',
    'variantId',
  ],
  type: 'object',
};

export const orderStatusHistorySchema = {
  properties: {
    changedBy: { type: 'string' },
    createdAt: { format: 'date-time', type: 'string' },
    id: { type: 'string' },
    reason: { type: 'string' },
    status: {
      enum: [
        'CANCELLED',
        'CONFIRMED',
        'DELIVERED',
        'FAILED',
        'PAID',
        'PAYMENT_PENDING',
        'PENDING',
        'PREPARING',
        'REFUNDED',
        'SHIPPED',
        'STOCK_RESERVED',
      ],
      type: 'string',
    },
  },
  required: ['createdAt', 'id', 'status'],
  type: 'object',
};

export const orderSchema = {
  example: {
    createdAt: '2026-06-06T12:00:00.000Z',
    currency: 'ARS',
    discountTotal: 0,
    grandTotal: 59990,
    id: 'order-123',
    idempotencyKey: 'checkout-20260606-001',
    items: [],
    orderNumber: 'NL-20260606-0001',
    paymentStatus: 'PENDING',
    shippingCost: 0,
    status: 'PAYMENT_PENDING',
    statusHistory: [],
    subtotal: 59990,
    taxTotal: 0,
    updatedAt: '2026-06-06T12:00:00.000Z',
    userId: 'f0a9c3b2-6d1e-4f8a-9b20-7c3d2e1f4a68',
  },
  properties: {
    billingAddressSnapshot: { additionalProperties: true, type: 'object' },
    createdAt: { format: 'date-time', type: 'string' },
    currency: { type: 'string' },
    discountTotal: { type: 'number' },
    grandTotal: { type: 'number' },
    id: { type: 'string' },
    idempotencyKey: { type: 'string' },
    items: { items: orderItemSchema, type: 'array' },
    orderNumber: { type: 'string' },
    paymentId: { type: 'string' },
    paymentStatus: { type: 'string' },
    shippingAddressSnapshot: { additionalProperties: true, type: 'object' },
    shippingCost: { type: 'number' },
    status: {
      enum: [
        'CANCELLED',
        'CONFIRMED',
        'DELIVERED',
        'FAILED',
        'PAID',
        'PAYMENT_PENDING',
        'PENDING',
        'PREPARING',
        'REFUNDED',
        'SHIPPED',
        'STOCK_RESERVED',
      ],
      type: 'string',
    },
    statusHistory: { items: orderStatusHistorySchema, type: 'array' },
    subtotal: { type: 'number' },
    taxTotal: { type: 'number' },
    updatedAt: { format: 'date-time', type: 'string' },
    userId: { type: 'string' },
  },
  required: [
    'createdAt',
    'currency',
    'discountTotal',
    'grandTotal',
    'id',
    'idempotencyKey',
    'items',
    'orderNumber',
    'shippingCost',
    'status',
    'statusHistory',
    'subtotal',
    'taxTotal',
    'updatedAt',
    'userId',
  ],
  type: 'object',
};

export const checkoutSessionSchema = {
  example: {
    checkoutUrl: 'https://www.mercadopago.com.ar/checkout/v1/redirect?pref_id=123',
    order: orderSchema.example,
    paymentProvider: 'MERCADO_PAGO',
    status: 'PAYMENT_READY',
  },
  properties: {
    checkoutUrl: { type: 'string' },
    order: orderSchema,
    payment: paymentSchema,
    paymentProvider: { enum: ['MERCADO_PAGO', 'MOCK', 'STRIPE'], type: 'string' },
    status: { enum: ['MOCK_PROCESSED', 'ORDER_CREATED', 'PAYMENT_READY'], type: 'string' },
  },
  required: ['order', 'paymentProvider', 'status'],
  type: 'object',
};

export const userProfileSchema = {
  example: {
    createdAt: '2026-06-06T12:00:00.000Z',
    email: 'customer@northlane.test',
    firstName: 'Lucas',
    id: 'profile-123',
    preferredCategories: ['camperas'],
    preferredSizes: ['M', 'L'],
    updatedAt: '2026-06-06T12:00:00.000Z',
    userId: 'f0a9c3b2-6d1e-4f8a-9b20-7c3d2e1f4a68',
  },
  properties: {
    birthDate: { type: 'string' },
    createdAt: { format: 'date-time', type: 'string' },
    documentNumber: { type: 'string' },
    documentType: { type: 'string' },
    email: { format: 'email', type: 'string' },
    firstName: { type: 'string' },
    gender: { type: 'string' },
    id: { type: 'string' },
    lastName: { type: 'string' },
    phone: { type: 'string' },
    preferredCategories: { items: { type: 'string' }, type: 'array' },
    preferredSizes: { items: { type: 'string' }, type: 'array' },
    updatedAt: { format: 'date-time', type: 'string' },
    userId: { type: 'string' },
  },
  required: ['createdAt', 'email', 'id', 'preferredCategories', 'preferredSizes', 'updatedAt', 'userId'],
  type: 'object',
};

export const addressSchema = {
  example: {
    alias: 'Casa',
    city: 'Buenos Aires',
    country: 'Argentina',
    createdAt: '2026-06-06T12:00:00.000Z',
    id: 'address-123',
    isDefault: true,
    phone: '+5491123456789',
    postalCode: 'C1001',
    province: 'Buenos Aires',
    recipientName: 'Lucas Gomez',
    street: 'Av. Corrientes',
    streetNumber: '1234',
    updatedAt: '2026-06-06T12:00:00.000Z',
    userId: 'f0a9c3b2-6d1e-4f8a-9b20-7c3d2e1f4a68',
  },
  properties: {
    alias: { type: 'string' },
    apartment: { type: 'string' },
    city: { type: 'string' },
    country: { type: 'string' },
    createdAt: { format: 'date-time', type: 'string' },
    id: { type: 'string' },
    isDefault: { type: 'boolean' },
    phone: { type: 'string' },
    postalCode: { type: 'string' },
    province: { type: 'string' },
    recipientName: { type: 'string' },
    references: { type: 'string' },
    street: { type: 'string' },
    streetNumber: { type: 'string' },
    updatedAt: { format: 'date-time', type: 'string' },
    userId: { type: 'string' },
  },
  required: [
    'alias',
    'city',
    'country',
    'createdAt',
    'id',
    'isDefault',
    'phone',
    'postalCode',
    'province',
    'recipientName',
    'street',
    'streetNumber',
    'updatedAt',
    'userId',
  ],
  type: 'object',
};

export const inventoryItemSchema = {
  example: {
    availableStock: 12,
    createdAt: '2026-06-06T12:00:00.000Z',
    id: 'inventory-item-123',
    isActive: true,
    productId: 'product-123',
    reservedStock: 0,
    sku: 'DEV-JACKET-BLK-M',
    stockOnHand: 12,
    updatedAt: '2026-06-06T12:00:00.000Z',
    variantId: 'variant-123',
  },
  properties: {
    availableStock: { type: 'number' },
    createdAt: { format: 'date-time', type: 'string' },
    id: { type: 'string' },
    isActive: { type: 'boolean' },
    productId: { type: 'string' },
    reservedStock: { type: 'number' },
    sku: { type: 'string' },
    stockOnHand: { type: 'number' },
    updatedAt: { format: 'date-time', type: 'string' },
    variantId: { type: 'string' },
  },
  required: [
    'availableStock',
    'createdAt',
    'id',
    'isActive',
    'productId',
    'reservedStock',
    'sku',
    'stockOnHand',
    'updatedAt',
    'variantId',
  ],
  type: 'object',
};

export const acceptedCommandSchema = {
  example: {
    accepted: true,
  },
  properties: {
    accepted: { type: 'boolean' },
  },
  required: ['accepted'],
  type: 'object',
};

export function arraySchema(itemSchema: object) {
  return {
    items: itemSchema,
    type: 'array',
  };
}
